#!/usr/bin/env python3
import requests
import sys

if __name__ == '__main__':
    url = f'{sys.argv[3]}/cart.php?a=add&pid='
    print(f'Testing {url} from {sys.argv[1]} to {sys.argv[2]}:')
    for i in range(int(sys.argv[1]), int(sys.argv[2]) + 1):
        print(f'Product ID {i}... ', end='')
        r = requests.get(f'{url}{i}', allow_redirects=False)
        if r.status_code != 302:
            print('X')
            continue
        if r.headers.get('Location').endswith("cart.php"):
            print('X')
            continue
        print('Valid')
